# Generated by Django 3.1.7 on 2021-03-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210314_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADM', 'Administrator'), ('MNG', 'Manager'), ('GST', 'Guest')], default='Administrator', max_length=20, verbose_name='Position'),
        ),
    ]
